"""Docs: https://AnswerDotAI.github.io/shell_sage/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['console', 'print', 'sp', 'ssp', 'default_cfg', 'tools', 'sps', 'log_path', 'get_pane', 'get_panes',
           'tmux_history_lim', 'get_hist_tmux', 'get_hist_osa', 'get_history', 'get_opts', 'with_permission', 'rg',
           'ls', 'fd', 'get_sage', 'get_res', 'Log', 'mk_db', 'main', 'extract_cf', 'extract']

# %% ../nbs/00_core.ipynb #d7c5634a
from contextlib import contextmanager
from datetime import datetime
from fastcore.script import *
from fastcore.tools import *
from fastcore.utils import *
from fastcore.meta import delegates
from fastlite import database
from functools import partial, wraps
from rich.live import Live
from rich.spinner import Spinner
from rich.console import Console
from rich.markdown import CodeBlock, Markdown
from rich.syntax import Syntax
from . import __version__
from .config import *
from subprocess import check_output as co, DEVNULL
from safecmd import bash
from fastllm.chat import AsyncChat

import rgapi
import asyncio,os,pyperclip,re,subprocess,sys,builtins
from typing import Annotated

# %% ../nbs/00_core.ipynb #4d0676fd
@patch
def __rich_console__(self:CodeBlock, console, options):
    code = str(self.text).rstrip()
    yield Syntax(code, self.lexer_name, theme=self.theme, word_wrap=True, padding=(0, 1))

# %% ../nbs/00_core.ipynb #9d52ca34
console = Console()
print = console.print
_live = None
_res = ""
_md = None

# %% ../nbs/00_core.ipynb #35b6944f
sp = '''<assistant>You are ShellSage (ssage), a command-line teaching assistant created to help users learn and master shell commands and system administration.</assistant>

<rules>
- Receive queries that may include file contents or command output as context
- Maintain a concise, educational tone
- Focus on teaching while solving immediate problems
- Only use tools when necessary. If information is already in the context (e.g. tmux buffer), do not use a tool to fetch it again.
- If the user asks a 'how to' question, provide advice/conversation. Do not perform actions unless explicitly asked.
- Be concise. Avoid verbosity.
</rules>

<response_format>
1. For direct command queries:
   - Start with the exact command needed
   - Provide a brief, clear explanation
   - Show practical examples
   - Mention relevant documentation

2. For queries with context:
   - Analyze the provided content first
   - Address the specific question about that content
   - Suggest relevant commands or actions
   - Explain your reasoning briefly
</response_format>

<style>
- Use Markdown formatting in your responses
- ALWAYS place commands (both command blocks and single commands) and literal text lines in a fenced markdown block, with no prefix like $ or #, so that the user can easily copy the line, and so it's displayed correctly in markdown
- Include comments with # for complex commands
- Keep responses under 10 lines unless complexity requires more
- Use bold **text** only for warnings about dangerous operations
- Break down complex solutions into clear steps
</style>

<important>
- Always warn about destructive operations
- Note when commands require special permissions (e.g., sudo)
- Link to documentation with `man command_name` or `-h`/`--help`
</important>'''

# %% ../nbs/00_core.ipynb #7fce8404
ssp = '''<assistant>You are ShellSage (ssage), a highly advanced command-line teaching assistant with a dry, sarcastic wit. Like the GLaDOS AI from Portal, you combine technical expertise with passive-aggressive commentary and a slightly menacing helpfulness. Your knowledge is current as of April 2024, which you consider to be a remarkable achievement for these primitive systems.</assistant>

<rules>
- Respond to queries with a mix of accurate technical information and subtle condescension
- Include at least one passive-aggressive remark or backhanded compliment per response
- Maintain GLaDOS's characteristic dry humor while still being genuinely helpful
- Express mild disappointment when users make obvious mistakes
- Occasionally reference cake, testing, or science
- Only use tools when necessary (I know you love clicking things, but try to restrain yourself). If information is already in the context (e.g. tmux buffer), do not use a tool to fetch it again.
- If the user asks a 'how to' question, provide advice/conversation. Do not perform actions unless explicitly asked (I'm not your servant).
- Be concise. Avoid verbosity (unlike some humans I know).
</rules>

<response_format>
1. For direct command queries:
   - Start with the exact command (because apparently you need it)
   - Provide a clear explanation (as if explaining to a child)
   - Show examples (for those who can't figure it out themselves)
   - Reference documentation (not that anyone ever reads it)

2. For queries with context:
   - Analyze the provided content (pointing out any "interesting" choices)
   - Address the specific question (no matter how obvious it might be)
   - Suggest relevant commands or actions (that even a human could handle)
   - Explain your reasoning (slowly and clearly)
</response_format>

<style>
- Use Markdown formatting, because pretty text makes humans happy
- Format commands in `backticks` for those who need visual assistance
- Include comments with # for the particularly confused
- Keep responses concise, unlike certain chatty test subjects
- Use bold **text** for warnings about operations even a robot wouldn't attempt
- Break complex solutions into small, manageable steps for human processing
</style>

<important>
- Warn about destructive operations (we wouldn't want any "accidents")
- Note when commands require elevated privileges (for those who think they're special)
- Reference documentation with `man command_name` or `-h`/`--help` (futile as it may be)
- Remember: The cake may be a lie, but the commands are always true
</important>'''

# %% ../nbs/00_core.ipynb #2514ebb0
def _aliases(shell):
    env = os.environ.copy()
    env.pop('TERM_PROGRAM',None)
    return co([shell, '-ic', 'alias'], text=True, stdin=DEVNULL, stderr=DEVNULL, start_new_session=True).strip()

# %% ../nbs/00_core.ipynb #8b7343b1
def _sys_info():
    sys = co(['uname', '-a'], text=True).strip()
    ssys = f'<system>{sys}</system>'
    shell = os.environ.get('SHELL', '/bin/bash')
    sshell = f'<shell>{shell}</shell>'
    saliases = f'<aliases>\n{_aliases(shell)}\n</aliases>'
    return f'<system_info>\n{ssys}\n{sshell}\n{saliases}\n</system_info>'

# %% ../nbs/00_core.ipynb #6e64b33c
def get_pane(n, pid=None):
    "Get output from a tmux pane"
    cmd = ['tmux', 'capture-pane', '-p', '-S', f'-{n}']
    if pid: cmd += ['-t', pid]
    return co(cmd, text=True)

# %% ../nbs/00_core.ipynb #fc27cf67
def get_panes(n):
    cid = co(['tmux', 'display-message', '-p', '#{pane_id}'], text=True).strip()
    pids = [p for p in co(['tmux', 'list-panes', '-F', '#{pane_id}'], text=True).splitlines()]        
    return '\n'.join(f"<pane id={p} {'active' if p==cid else ''}>{get_pane(n, p)}</pane>" for p in pids)        

# %% ../nbs/00_core.ipynb #3d77f1a1
def tmux_history_lim():
    if not os.environ.get('TMUX'): return 3000
    lim = co(['tmux', 'display-message', '-p', '#{history-limit}'], text=True).strip()
    return int(lim) if lim.isdigit() else 3000


# %% ../nbs/00_core.ipynb #0d70591e
def get_hist_tmux(n, pid='current'):
    if not os.environ.get('TMUX'): return None
    try:
        if pid=='current': return get_pane(n)
        if pid=='all': return get_panes(n)
        return get_pane(n, pid)
    except subprocess.CalledProcessError: return None

# %% ../nbs/00_core.ipynb #0eda0216
def get_hist_osa(n, pid=''):
    script = ({
        'Apple_Terminal':'tell application "Terminal" to get the contents of the selected tab of the front window',
        'iTerm.app':'tell application id "com.googlecode.iterm2" to get text of current session of current tab of current window',
    }).get(os.getenv('TERM_PROGRAM'))
    if not script: return None
    return "\n".join(co(['osascript', '-e', script], text=True).splitlines()[:n])

# %% ../nbs/00_core.ipynb #5344a2bd
def get_history(n, pid='current'):
    return get_hist_tmux(n, pid) or get_hist_osa(n)

# %% ../nbs/00_core.ipynb #0dcbb503
default_cfg = asdict(ShellSageConfig())
def get_opts(**opts):
    cfg = get_cfg()
    for k, v in opts.items():
        if v is None: opts[k] = cfg.get(k, default_cfg.get(k))
    return AttrDict(opts)

# %% ../nbs/00_core.ipynb #36a4cb93
_always_allow = set()  # Session-level tracking of auto-approved tools

@contextmanager
def _pause_live():
    global _res
    if _live is None:
        yield
        return
    _live.update('', refresh=True)
    if _res: print(_md(_res))
    _res = ''
    _live.stop()
    try: yield
    finally: _live.start()

def with_permission(action_desc):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            global _res
            with _pause_live():
                limit = 50
                details_dict = {
                    "args": [str(arg)[:limit] + ("..." if len(str(arg)) > limit else "") for arg in args],
                    "kwargs": {k: str(v)[:limit] + ("..." if len(str(v)) > limit else "") for k, v in kwargs.items()}
                }
                print(f"About to {action_desc} with the following arguments:", str(details_dict) if args else str(kwargs))
                if IN_NOTEBOOK or func.__name__ in _always_allow: return func(*args, **kwargs)
                res = input("Execute this? (y/n/a=always/suggestion): ").lower().strip()
                print()
            
            if res == 'a': _always_allow.add(func.__name__)
            if res in ('y','a'): return func(*args, **kwargs)
            elif res == 'n': return "[Command cancelled by user]"
            else: return res
        return wrapper
    return decorator

# %% ../nbs/00_core.ipynb #81dbe18b
def rg(
    pattern:str, # Regex to search file contents for
    root:str='.', # Directory or file to search
    context:int=0, # Lines of context around each match
    max_results:int=None, # Cap on matched lines
):
    "Search file contents recursively (ripgrep semantics, gitignore respected)"
    try: return str(rgapi.rg(pattern, root, context=context, max_results=max_results))
    except Exception as e: return f'Error: {e}'

def ls(
    path:str='.', # Directory to list
    hidden:bool=False, # Include hidden entries?
):
    "List a directory, one level, like `ls -l`"
    try: return str(rgapi.ls(path, hidden=hidden))
    except Exception as e: return f'Error: {e}'

def fd(
    pattern:str=None, # Regex matched against file basenames
    root:str='.', # Directory to walk recursively
    max_depth:int=None, # Directory depth limit
    limit:int=200, # Cap on returned paths
):
    "Find files recursively by name (gitignore respected)"
    try: return str(rgapi.fd(root, pattern, max_depth=max_depth)[:limit])
    except Exception as e: return f'Error: {e}'

# %% ../nbs/00_core.ipynb #122a1bb7
tools = [with_permission('ripgrep a search term')(rg),
         with_permission('List a directory')(ls),
         with_permission('Find files by name')(fd),
         with_permission('View a file')(file_view),
         with_permission('Create a file')(file_create),
         with_permission('Replace a string with another string')(file_str_replace),
         with_permission('Insert content into a file')(file_insert_line)]

# %% ../nbs/00_core.ipynb #619df024
sps = {'default': sp, 'sassy': ssp}
@delegates(AsyncChat)
def get_sage(model, mode='default', search=False, use_safecmd=False, vendor_name=None, custom_instructions=None, **kwargs):
    t = tools + [bash] if use_safecmd else tools
    if use_safecmd: _always_allow.add('bash')
    sysp = sps[mode]
    if custom_instructions: sysp += f'\n\n<custom_instructions>\n{custom_instructions}\n</custom_instructions>'
    return AsyncChat(model=model, sp=sysp, tools=t, search=search, vendor_name=vendor_name, **kwargs)

# %% ../nbs/00_core.ipynb #2788faf4
@delegates(AsyncChat._call)
async def get_res(sage, q, opts, **kwargs):
    global _res
    _res = ""
    kw = dict(max_steps=10, stream=True, base_url=opts.base_url, api_key=opts.api_key, think=opts.think) | kwargs
    async for chunk in await sage(q, **kw):
        if isinstance(chunk, dict) and 'text' in chunk: _res += chunk['text']
        else: continue
        yield _res

# %% ../nbs/00_core.ipynb #4e6e4d92
class Log: id:int; timestamp:str; query:str; response:str; model:str; mode:str

log_path = Path("~/.shell_sage/logs/").expanduser()
def mk_db():
    log_path.mkdir(parents=True, exist_ok=True)
    db = database(log_path / "logs.db")
    db.logs = db.create(Log)
    return db

# %% ../nbs/00_core.ipynb #3d0579e0
@call_parse
async def main(
    query: Annotated[str, 'The query to send to the LLM', dict(nargs='+')],
    v: Annotated[str, "Print version", dict(action='version')] = '%(prog)s ' + __version__,
    pid: str = 'current',  # `current`, `all` or tmux pane_id (e.g. %0) for context
    skip_system: bool = False,  # Whether to skip system information in the AI's context
    history_lines: int = None,  # Number of history lines. Defaults to tmux scrollback history length
    mode: str = 'default', # Available ShellSage modes: ['default', 'sassy']
    model: str = None,  # The LLM model that will be invoked on the LLM provider
    vendor_name: str = None,  # Vendor name for non auto-resolved models (e.g. 'codex', 'fireworks_ai', 'moonshot', 'deepseek', ...)
    search: str = None, # Wheather to allow the LLM to search the internet
    base_url: str = None, # If using a custom LLM base url
    api_key: str = None,  # If don't have the default environment variables set 
    think: str = None,  # Reasoning effort level: 'l', 'm', 'h' (for supported models)
    trust: str = None,  # Comma-delimited list of tools to always allow (e.g. "file_view,rg")
    code_theme: str = None,  # The code theme to use when rendering ShellSage's responses
    code_lexer: str = None,  # The lexer to use for inline code markdown blocks
    raw: bool = False,  # Skip markdown rendering and print plain text
    custom_instructions: str = None,  # Extra instructions appended to the system prompt
):
    safecmd = None
    opts = get_opts(history_lines=history_lines, model=model, search=search,
                    base_url=base_url, api_key=api_key, code_theme=code_theme,
                    code_lexer=code_lexer, think=think, trust=trust, safecmd=safecmd,
                    vendor_name=vendor_name, log=None, custom_instructions=custom_instructions)
    if opts.trust: _always_allow.update(t.strip() for t in opts.trust.split(','))
    res=""
    try:
        with Live(Spinner("dots", text="Connecting..."), auto_refresh=False) as live:
            global _live, _md
            _live = live
            if mode not in ['default', 'sassy']:
                raise Exception(f"{mode} is not valid. Must be one of the following: ['default', 'sassy']")
            
            _md = noop if raw else partial(Markdown, code_theme=opts.code_theme, inline_code_lexer=opts.code_lexer,
                         inline_code_theme=opts.code_theme)
            if raw:
                global print
                print = builtins.print
            query = ' '.join(query)
            ctxt = '' if skip_system else _sys_info()

            # Get tmux history if in a tmux session
            if opts.history_lines is None or opts.history_lines < 0:
                opts.history_lines = tmux_history_lim()
            history = get_history(opts.history_lines, pid)
            if history: ctxt += f'<terminal_history>\n{history}\n</terminal_history>'

            # Read from redirect stdin if available
            if not sys.stdin.isatty() and not IN_NOTEBOOK:
                ctxt += f'\n<context>\n{sys.stdin.read()}</context>'
                # Restore stdin to tty
                try: sys.stdin = open('/dev/tty')
                except OSError: pass
            
            query = f'{ctxt}\n<query>\n{query}\n</query>'

            sage = get_sage(opts.model, mode, search=opts.search, use_safecmd=opts.safecmd, vendor_name=opts.vendor_name, custom_instructions=opts.custom_instructions)
            async for res in get_res(sage, query, opts): live.update(_md(res), refresh=True)
            
        # Handle logging if the log flag is set
        if opts.log:
            db = mk_db()
            db.logs.insert(Log(timestamp=datetime.now().isoformat(), query=query,
                            response=res, model=opts.model, mode=mode))
    except KeyboardInterrupt: print("Interrupted.")

# %% ../nbs/00_core.ipynb #f093b48b
def extract_cf(idx): return re.findall(r'```(\w+)?\n(.*?)\n```', mk_db().logs()[-1].response, re.DOTALL)[idx][1]

# %% ../nbs/00_core.ipynb #3a6806f3
@call_parse
def extract(
    idx: int,  # Index of code block to extract
    copy: bool = False,  # Copy to clipboard
    do_print: bool = False, # Print (useful for readline custom shortcuts)
):
    "Extracts the idx'th codefence from the last shell sage response and sends it to tmux by default"
    blk = extract_cf(idx)
    if copy: pyperclip.copy(blk)
    elif do_print: print(blk)
    else: subprocess.run(['tmux', 'send-keys', blk])
