# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_logview.ipynb.

# %% auto #0
__all__ = ['log2json', 'log2fm', 'log2md', 'ssage_log']

# %% ../nbs/02_logview.ipynb #d7c5634a
import sys, re, json, builtins
from pathlib import Path
from datetime import datetime
from fastcore.script import call_parse
from fastcore.xtras import asdict
from fastlite import database
from .config import ShellSageConfig, get_cfg
from .core import log_path, Log, mk_db

# %% ../nbs/02_logview.ipynb #972d9a11
_log_field_names = tuple(Log.__annotations__.keys())
_front_matter = ('id', 'timestamp', 'model', 'mode')

# %% ../nbs/02_logview.ipynb #a138508f
def _q_1line(query, lim=100):
    m = re.search(r'<query>\s*(.*?)\s*</query>', query or '', re.DOTALL | re.IGNORECASE)
    s = re.sub(r'\s+', ' ', (m.group(1) if m else (query or '')).strip(), flags=re.S)
    return s[: lim] + '...' if len(s) > lim else s

# %% ../nbs/02_logview.ipynb #07ecab02
def log2json(r, **kw): return json.dumps({k: r.get(k) for k in _log_field_names}, default=str)

# %% ../nbs/02_logview.ipynb #9ecf86a3
def log2fm(r, **kw):
    ks = [k for k in _front_matter if k in r]
    if not ks: return ''
    return f'''---\n{'\n'.join(f"{k}: {r.get(k)}" for k in ks)}\n---\n'''

# %% ../nbs/02_logview.ipynb #39568ba6
def _parse_query(qry):
    mtch = re.search(r'\A(.*)\n<query>\s*(.*?)\s*</query>\Z', qry, re.DOTALL | re.IGNORECASE)
    ctx, qry = mtch.groups() if mtch else ('','')
    return ctx, qry

def _md_parts(r, frontmatter):
    fm = log2fm(r)+'\n\n' if frontmatter else ''
    ctx, qry = _parse_query(r.get('query', ''))
    res = r.get('response')
    return fm, ctx, qry, res

def log2md(r, frontmatter=False, context=False, **kw):
    fm, ctx, qry, res = _md_parts(r, frontmatter)
    if context and ctx:
        ctx = f'''```xml\n{ctx}\n```\n\n'''
        ctx = f'''<details class='context-details'><summary>context</summary>\n\n{ctx}\n\n</details>\n\n'''
    else: ctx = ''
    turn = f'''## AI Prompt\n{qry}\n## AI Response\n{res}'''
    return f"{fm}{ctx}{turn}"

# %% ../nbs/02_logview.ipynb #ad1deabc
_pr = builtins.print
def _die(msg, code=2): _pr(msg, file=sys.stderr); raise SystemExit(code)

def _active_db_path(): return log_path / 'logs.db'

def _ls():
    log_path.mkdir(parents=True, exist_ok=True)
    for p in sorted(log_path.glob('*.db'), key=lambda x: x.name):
        st = p.stat()
        dt = datetime.fromtimestamp(st.st_mtime).isoformat()
        act = 'active' if p.name == 'logs.db' else '-'
        _pr(f"{p.name}	{act}	{st.st_size}	{dt}")

def _db(log_db):
    pth = (Path(log_db) if log_db else _active_db_path()).expanduser()
    dcfg = asdict(ShellSageConfig())
    log_en = bool(get_cfg().get('log', dcfg['log']))
    if not pth.exists():
        _pr('ssage_log: no log database at', pth, file=sys.stderr)
        if not log_en:
            _pr(
                '  Set `log = True` in ~/.config/shell_sage/shell_sage.conf and run `ssage` to create logs.',
                file=sys.stderr,
            )
        else: _pr('  Run `ssage` to create a log if this path is new.', file=sys.stderr)
        raise SystemExit(1)
    db = database(pth)
    db.logs = db.create(Log)
    c = (db.q('select count(*) as c from log')[0] or {'c': 0})['c']
    if c == 0:
        _pr(
            'ssage_log: log database is empty; run `ssage` to record entries (with `log = True` in your config).',
            file=sys.stderr,
        )
        if not log_en:
            _pr('  `log` is false in your config; enable it to save new sessions to the database.', file=sys.stderr)
        return
    return db

def _info(out, db):
    w = (open(out, 'w', encoding='utf-8') if out else None)
    f = w or sys.stdout
    try:
        rows = db.q('select * from log order by timestamp asc, id asc') or []
        for i, r in enumerate(rows, 1):
            _pr(f"{i}	{r.get('timestamp', '')}	{_q_1line(r.get('query', ''))}", file=f)
    finally:
        if w: w.close()

def _rows(all, last, db):
    if all: return list(db.q('select * from log order by timestamp asc, id asc') or [])
    if last < 1: _die('ssage_log: --last must be at least 1', 2)
    tail = db.q('select * from log order by timestamp desc, id desc limit ?', (last,)) or []
    tail.reverse()
    return tail

# %% ../nbs/02_logview.ipynb #7c7299ed
def _to_nb(rows, **kw):
    return {
        'cells': [{'cell_type': 'markdown', 'metadata': {}, 'source': log2md(r, **kw)} for r in rows],
        'metadata': {}, 'nbformat': 4, 'nbformat_minor': 5,
    }

def _show(all, last, format, out, db, frontmatter=False, context=False):
    rows = _rows(all, last, db)
    w = open(out, 'w', encoding='utf-8') if out else None
    f = w or sys.stdout
    fmt = log2json if format == 'json' else log2md
    try:
        if format in ('json', 'md'):
            for r in rows: f.write(fmt(r, frontmatter=frontmatter, context=context) + '\n')
        else:
            json.dump(_to_nb(rows, frontmatter=frontmatter, context=context), f, ensure_ascii=False)
            f.write('\n')
    finally:
        if w: w.close()

# %% ../nbs/02_logview.ipynb #b8e87d10
def _prune_db():
    log_path.mkdir(parents=True, exist_ok=True)
    src = _active_db_path()
    if not src.exists(): _die(f'ssage_log: active database not found at {src}', 1)
    ts = datetime.now().strftime('%Y-%m-%d-%H%M%S')
    dst = log_path / f'logs-{ts}.db'
    i = 1
    while dst.exists():
        dst = log_path / f'logs-{ts}-{i}.db'
        i += 1
    src.rename(dst)
    mk_db()
    _pr(f'pruned {src.name} -> {dst.name}')

# %% ../nbs/02_logview.ipynb #d3a5d4f7
@call_parse
def ssage_log(
    log_db: str|None = None,  # Path to sqlite log database; default: active file at ~/.shell_sage/logs/logs.db
    ls: bool = False,  # List .db files in the log directory and exit
    info: bool = False,  # Print order, timestamp, and one-line user query for every row; omits other modes
    prune: bool = False,  # Rotate active logs.db to logs-YYYY-MM-DD-HHMMSS.db and recreate empty logs.db
    all: bool = False,  # Include all rows in time order, oldest first (overrides --last)
    last: int = 1,  # How many of the *most recent* rows to print, oldest of that set first, unless you pass --all
    format: str = 'json',  # output: json, md, or nb (for default export only; not --info)
    frontmatter: bool = False,  # For --format md, include frontmatter with id/timestamp/model/mode
    context: bool = False,  # For --format md, include captured context in a collapsible details block
    out: str|None = None,  # Write to this file instead of stdout
):
    "Print logged ShellSage Q&A from the sqlite log database."
    if format not in ('json', 'md', 'nb'): _die(f'ssage_log: --format must be json, md, or nb, not {format!r}', 2)
    if info and (all or any(a == '--last' for a in sys.argv[1:])):
        _die('ssage_log: do not use --info together with --all or --last', 2)
    if ls: return _ls()
    if prune: return _prune_db()
    if not (db := _db(log_db)): return
    if info: return _info(out, db)
    _show(all, last, format, out, db, frontmatter=frontmatter, context=context)
