# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tools.ipynb.

# %% auto 0
__all__ = ['tools', 'ns']

# %% ../nbs/02_tools.ipynb 2
from claudette.core import *
from claudette.text_editor import *
from pathlib import Path
from subprocess import run
from toolslm.funccall import *

# %% ../nbs/02_tools.ipynb 5
tools = {'anthropic': [text_editor_conf['sonnet'], search_conf()],
         'openai': [{"type": "web_search_preview"}, view, create, insert, str_replace]}

# %% ../nbs/02_tools.ipynb 7
ns = {'anthropic': mk_ns(tools['anthropic'] + [str_replace_based_edit_tool]), 'openai': mk_ns(tools['openai'])}
